services:
  - type: web
    name: nutrilens-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: MODEL_NAME
        value: efficientnet
      - key: CKPT_PATH
        value: model/efficientnet_best.pth
      - key: CLASS_PATH
        value: model/selected_classes.txt
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/model
      sizeGB: 1
