services:
  - type: web
    name: nutrilens-api
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --bind 0.0.0.0:$PORT --worker-class sync --max-requests 10 --max-requests-jitter 5
    envVars:
      - key: MODEL_NAME
        value: efficientnet
      - key: CKPT_PATH
        value: model/efficientnet_best.pth
      - key: CLASS_PATH
        value: model/selected_classes_efficientnet.txt
